/**
 * PWA Generator — automatically creates manifest.json, Service Worker,
 * and simple SVG icons for any kele-generated project.
 *
 * Called automatically after GameGenerator writes index.html.
 * No user action required. Zero external dependencies.
 */

import { join } from 'path';
import { mkdir, writeFile } from 'fs/promises';
import type { GeneratedPage } from '../orchestrator/types.js';

export interface PWAGenerationResult {
  manifestPath: string;
  swPath: string;
  icon192Path: string;
  icon512Path: string;
}

export interface PWAOptions {
  name?: string;
  shortName?: string;
  themeColor?: string;
  backgroundColor?: string;
  description?: string;
}

/**
 * Generate all PWA assets for a project directory.
 */
export async function generatePWA(
  projectRoot: string,
  options: PWAOptions = {},
  pages?: GeneratedPage[],
): Promise<PWAGenerationResult> {
  const name = options.name ?? 'kele Game';
  const shortName = options.shortName ?? name.slice(0, 12);
  const themeColor = options.themeColor ?? '#1a1a2e';
  const backgroundColor = options.backgroundColor ?? '#16213e';
  const description = options.description ?? 'A game generated by kele';

  const iconsDir = join(projectRoot, 'icons');
  await mkdir(iconsDir, { recursive: true });

  // Generate manifest.json
  const manifestPath = join(projectRoot, 'manifest.json');
  const manifest = {
    name,
    short_name: shortName,
    description,
    start_url: './',
    display: 'standalone',
    background_color: backgroundColor,
    theme_color: themeColor,
    orientation: 'any',
    icons: [
      { src: './icons/icon-192.svg', sizes: '192x192', type: 'image/svg+xml' },
      { src: './icons/icon-512.svg', sizes: '512x512', type: 'image/svg+xml' },
    ],
  };
  await writeFile(manifestPath, JSON.stringify(manifest, null, 2), 'utf-8');

  // Generate Service Worker with all pages cached
  const swPath = join(projectRoot, 'sw.js');
  const swCode = generateServiceWorker(pages);
  await writeFile(swPath, swCode, 'utf-8');

  // Generate SVG icons (zero dependencies, scalable)
  const letter = extractInitial(name);
  const icon192Path = join(iconsDir, 'icon-192.svg');
  const icon512Path = join(iconsDir, 'icon-512.svg');
  const svgContent = generateSVGIcon(letter, backgroundColor, themeColor);
  await writeFile(icon192Path, svgContent, 'utf-8');
  await writeFile(icon512Path, svgContent, 'utf-8');

  return { manifestPath, swPath, icon192Path, icon512Path };
}

/**
 * Generate a simple Service Worker with Cache First strategy.
 * If pages are provided, caches all sub-pages for offline use.
 */
function generateServiceWorker(pages?: GeneratedPage[]): string {
  const cacheUrls = [
    './',
    './index.html',
    './manifest.json',
  ];

  if (pages && pages.length > 0) {
    for (const p of pages) {
      cacheUrls.push(`./${p.fileName}`);
    }
  }

  cacheUrls.push('./data-bridge.js');
  cacheUrls.push('./icons/icon-192.svg');
  cacheUrls.push('./icons/icon-512.svg');

  const urlsToCacheJson = JSON.stringify(cacheUrls, null, 2);

  return `const CACHE_NAME = 'kele-game-v1';
const urlsToCache = ${urlsToCacheJson};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(urlsToCache))
  );
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) =>
      Promise.all(
        cacheNames
          .filter((name) => name !== CACHE_NAME)
          .map((name) => caches.delete(name))
      )
    )
  );
  self.clients.claim();
});

self.addEventListener('fetch', (event) => {
  event.respondWith(
    caches.match(event.request).then((response) => {
      if (response) return response;
      return fetch(event.request).catch(() => {
        if (event.request.mode === 'navigate') {
          return caches.match('./index.html');
        }
      });
    })
  );
});
`;
}

/**
 * Inject PWA tags into an HTML string.
 * Adds manifest link and service worker registration script.
 */
export function injectPWATags(html: string): string {
  // Avoid double-injection
  if (html.includes('rel="manifest"')) return html;

  const pwaBlock = `  <link rel="manifest" href="manifest.json">
  <meta name="theme-color" content="#1a1a2e">
  <script>
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.register('sw.js').catch(function() { /* ignore */ });
    }
  </script>`;

  // Insert before closing </head>, or at start if no <head>
  if (html.includes('</head>')) {
    return html.replace('</head>', `${pwaBlock}\n</head>`);
  }

  // Fallback: insert after <html> tag or at very beginning
  if (html.includes('<html')) {
    return html.replace(/<html[^>]*>/, (match) => `${match}\n<head>\n${pwaBlock}\n</head>`);
  }

  return `<head>\n${pwaBlock}\n</head>\n${html}`;
}

/**
 * Extract the first English letter or Chinese character initial from a name.
 */
function extractInitial(name: string): string {
  const first = name.trim()[0];
  if (!first) return 'K';
  if (/[a-zA-Z]/.test(first)) return first.toUpperCase();
  // For Chinese, use the Unicode code point mod 26 to pick a letter
  const code = first.charCodeAt(0);
  if (code >= 0x4e00 && code <= 0x9fff) {
    return String.fromCharCode(65 + (code % 26));
  }
  return 'K';
}

/**
 * Generate a simple SVG icon with a colored circle and initial letter.
 */
function generateSVGIcon(letter: string, bgColor: string, circleColor: string): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
  <rect width="512" height="512" fill="${escapeXml(bgColor)}"/>
  <circle cx="256" cy="256" r="180" fill="${escapeXml(circleColor)}"/>
  <text x="256" y="296" font-family="Arial,sans-serif" font-size="240" font-weight="bold"
        fill="white" text-anchor="middle" dominant-baseline="central">${escapeXml(letter)}</text>
</svg>`;
}

function escapeXml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
