/**
 * kele — Shared Type Definitions
 *
 * Core data models for the Idea-to-Monetization workflow engine.
 */

export type CreativeType = 'game' | 'music' | 'content' | 'tool' | 'bot' | 'unknown';

export type MonetizationChannel =
  | 'wechat-miniprogram'
  | 'douyin'
  | 'steam'
  | 'web'
  | 'app-store'
  | 'google-play'
  | 'unknown';

export type Complexity = 'simple' | 'medium' | 'complex';

export type ProjectStatus =
  | 'pending'
  | 'initialized'
  | 'planning'
  | 'executing'
  | 'completed'
  | 'failed';

export type TaskStatus = 'pending' | 'running' | 'completed' | 'failed' | 'skipped';

export type AIProvider = 'deepseek' | 'qwen' | 'claude' | 'openai' | 'mock';

/**
 * A user's raw idea, parsed into structured form.
 */
export interface Idea {
  /** Unique identifier */
  id: string;
  /** Original user input */
  rawText: string;
  /** Detected creative domain */
  type: CreativeType;
  /** Detected monetization channel */
  monetization: MonetizationChannel;
  /** Estimated complexity */
  complexity: Complexity;
  /** Extracted keywords for context */
  keywords: string[];
  /** Timestamp */
  createdAt: string;
}

/**
 * A single acceptance criterion for validating a sub-project.
 * Generated by the Incubator, executed by kele's test runner.
 */
export interface AcceptanceCriterion {
  /** Human-readable description of what to verify */
  description: string;
  /** Category of verification */
  type: 'functional' | 'visual' | 'performance' | 'compatibility' | 'security';
  /** How to verify: "open", "click", "check-text", "check-element", "play-game", "load-url" */
  action: string;
  /** Target selector, URL, or coordinate for the action */
  target?: string;
  /** Expected result after performing the action */
  expected: string;
  /** Whether this criterion blocks sub-project acceptance */
  critical: boolean;
}

/**
 * A sub-project generated by the Incubator.
 * Each sub-project is a discrete deliverable (e.g. game-dev, deployment, store-submit).
 */
/**
 * Monetization route recommendation.
 */
export interface MonetizationRoute {
  platform: string;
  platformLabel: string;
  score: number;
  reason: string;
  requirements: string[];
  missingRequirements: string[];
  estimatedDays: number;
  effort: 'low' | 'medium' | 'high';
  autoDeployable: boolean;
  needsSoftWareCopyright: boolean;
  revenueModel: string;
  payoutMethod: string;
  estimatedRevenue: string;
}

export interface SubProject {
  id: string;
  name: string;
  description: string;
  type: string;
  /** Absolute path where this sub-project will be generated */
  targetDir: string;
  /** IDs of sub-projects that must complete before this one starts */
  dependencies: string[];
  status: ProjectStatus;
  createdAt: string;
  /** How this sub-project serves the monetization goal (core/supporting/optional) */
  monetizationRelevance?: 'core' | 'supporting' | 'optional';
  /** Estimated effort: hours or days */
  estimatedEffort?: string;
  /** Whether this sub-project is on the critical path (blocks monetization) */
  criticalPath?: boolean;
  /** Risk level for this sub-project */
  riskLevel?: 'low' | 'medium' | 'high';
  /** Acceptance criteria generated by incubator — kele executes these to validate */
  acceptanceCriteria?: AcceptanceCriterion[];
}

/**
 * An executable task within a sub-project.
 */
export interface Task {
  id: string;
  subProjectId: string;
  title: string;
  description: string;
  /** Determines AI routing */
  complexity: Complexity;
  status: TaskStatus;
  /** Which AI provider executed this task */
  aiProvider?: AIProvider;
  /** Raw output from the AI */
  result?: string;
  /** Error message if failed */
  error?: string;
  /** If set, this task is an upgrade of the parent task */
  parentTaskId?: string;
  /** Version number — increments on each upgrade */
  version: number;
  createdAt: string;
  completedAt?: string;
}

/**
 * A kele project — the top-level container for a user's idea.
 */
export interface Project {
  id: string;
  name: string;
  idea: Idea;
  subProjects: SubProject[];
  tasks: Task[];
  status: ProjectStatus;
  /** Root directory where all sub-projects are generated */
  rootDir: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * Result of parsing a user's raw idea.
 */
export interface ParseResult {
  success: boolean;
  idea?: Idea;
  error?: string;
}

/**
 * Result of incubating an idea into sub-projects.
 */
export interface IncubateResult {
  success: boolean;
  subProjects?: SubProject[];
  error?: string;
}

/**
 * Result of planning a sub-project into tasks.
 */
export interface PlanResult {
  success: boolean;
  tasks?: Task[];
  error?: string;
}

/**
 * Result of executing a single task.
 */
export interface ExecuteResult {
  success: boolean;
  output?: string;
  error?: string;
}
