import type { AIAdapter } from './base.js';

/**
 * Mock AI Adapter — returns canned responses for testing and development.
 * Zero cost, zero latency. Used when no real AI keys are configured.
 */

export class MockAdapter implements AIAdapter {
  readonly name = 'mock';

  isAvailable(): boolean {
    return true;
  }

  async execute(prompt: string): Promise<string> {
    const lower = prompt.toLowerCase();

    // Coding tasks: return JSON with files
    if (lower.includes('project structure') || lower.includes('初始化')) {
      return JSON.stringify({
        files: [
          { path: 'package.json', content: '{\n  "name": "project",\n  "version": "1.0.0"\n}' },
          { path: 'src/index.ts', content: '// Entry point\nconsole.log("Hello kele!");' },
          { path: 'README.md', content: '# Project\n\nGenerated by kele.' },
        ],
        notes: 'Project initialized with basic structure',
      });
    }

    if (lower.includes('core feature')) {
      return JSON.stringify({
        files: [
          { path: 'src/game.ts', content: 'export class Game {\n  start() {\n    console.log("Game started!");\n  }\n}' },
        ],
        notes: 'Core gameplay implemented',
      });
    }

    if (lower.includes('test')) {
      return JSON.stringify({
        files: [
          { path: 'tests/game.test.ts', content: 'import { test, expect } from "vitest";\n\ntest("game starts", () => {\n  expect(true).toBe(true);\n});' },
        ],
        notes: 'Tests written',
      });
    }

    // Research / analysis mode
    if (lower.includes('research') || lower.includes('分析') || lower.includes('报告') || lower.includes('分析师')) {
      return `## 1. 产品分析\n这是一款消除类休闲游戏，核心玩法是三消匹配，目标受众是18-35岁休闲玩家。\n\n## 2. 变现分析\n主要通过广告变现（插屏广告+激励视频）和道具内购。留存率高，适合流量变现。\n\n## 3. 市场洞察\n关键成功因素：简单易上手、关卡难度曲线合理、每日任务和排行榜增加粘性。\n\n## 4. 建议\n- 核心玩法：经典三消+特殊道具\n- USP：加入社交排行榜和好友助力\n- 推荐平台：微信小程序（用户基数大，传播快）\n- 复杂度：中等\n- MVP功能：50关、3种道具、排行榜\n\n## 5. 关键词\n消除游戏、三消、休闲、微信、小程序、广告变现、内购、排行榜`;
    }

    // Default: return empty files + notes
    return JSON.stringify({
      files: [
        { path: 'task-notes.md', content: `# Task Notes\n\n${prompt.slice(0, 200)}...\n\n(Mocked execution — configure a real AI provider for actual code generation)` },
      ],
      notes: 'Mock execution completed',
    });
  }
}
