import type { AIAdapter } from './base.js';

/**
 * Mock AI Adapter — returns canned responses for testing and development.
 * Zero cost, zero latency. Used when no real AI keys are configured.
 */

export class MockAdapter implements AIAdapter {
  readonly name = 'mock';

  isAvailable(): boolean {
    return true;
  }

  async execute(prompt: string): Promise<string> {
    // Return a structured mock response based on prompt keywords
    const lower = prompt.toLowerCase();

    if (lower.includes('project structure') || lower.includes('初始化')) {
      return JSON.stringify({
        files: [
          { path: 'package.json', content: '{"name": "project", "version": "1.0.0"}' },
          { path: 'src/index.ts', content: '// Entry point\nconsole.log("Hello kele!");' },
          { path: 'README.md', content: '# Project\n\nGenerated by kele.' },
        ],
      });
    }

    if (lower.includes('test') || lower.includes('测试')) {
      return JSON.stringify({
        files: [
          { path: 'tests/index.test.ts', content: 'import { test, expect } from "vitest";\ntest("smoke", () => expect(true).toBe(true));' },
        ],
      });
    }

    return JSON.stringify({
      message: `Mock AI received prompt: "${prompt.slice(0, 100)}..."`,
      note: 'Configure a real AI provider with `kele config` for actual code generation.',
    });
  }
}
